# Generated by Django 5.2.13 on 2026-05-08 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0004_tag_post_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_genres', models.JSONField(blank=True, default=dict)),
                ('top_tags', models.JSONField(blank=True, default=dict)),
                ('exploration_ratio', models.FloatField(default=0.1)),
                ('last_interaction_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interest_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feed_user_interest_profile',
            },
        ),
        migrations.CreateModel(
            name='PostAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('unique_viewers', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('comments', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('bookmarks', models.PositiveIntegerField(default=0)),
                ('reports', models.PositiveIntegerField(default=0)),
                ('complete_reads', models.PositiveIntegerField(default=0)),
                ('rereads', models.PositiveIntegerField(default=0)),
                ('quick_scrolls', models.PositiveIntegerField(default=0)),
                ('total_reading_time_ms', models.PositiveBigIntegerField(default=0)),
                ('avg_read_progress', models.FloatField(default=0)),
                ('engagement_score', models.FloatField(default=0)),
                ('last_engagement_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='posts.post')),
            ],
            options={
                'db_table': 'feed_post_analytics',
                'indexes': [models.Index(fields=['-engagement_score'], name='feed_post_a_engagem_d9f9ee_idx'), models.Index(fields=['-updated_at'], name='feed_post_a_updated_4f1390_idx')],
            },
        ),
        migrations.CreateModel(
            name='PostDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_pool', models.PositiveIntegerField(default=1)),
                ('current_pool_size', models.PositiveIntegerField(default=500)),
                ('next_pool_size', models.PositiveIntegerField(default=5000)),
                ('last_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('engagement_rate', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('hold', 'Hold'), ('graduated', 'Graduated')], default='active', max_length=20)),
                ('delivered_impressions', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distribution', to='posts.post')),
            ],
            options={
                'db_table': 'feed_post_distribution',
                'indexes': [models.Index(fields=['status', 'current_pool'], name='feed_post_d_status_6ef1e5_idx'), models.Index(fields=['-updated_at'], name='feed_post_d_updated_a31b5b_idx')],
            },
        ),
        migrations.CreateModel(
            name='PostInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal', models.CharField(choices=[('view', 'View'), ('scroll', 'Scroll'), ('like', 'Like'), ('comment', 'Comment'), ('share', 'Share'), ('bookmark', 'Bookmark'), ('report', 'Report')], max_length=20)),
                ('reading_time_ms', models.PositiveIntegerField(default=0)),
                ('read_progress', models.FloatField(default=0)),
                ('completed_read', models.BooleanField(default=False)),
                ('reread_count', models.PositiveIntegerField(default=0)),
                ('is_quick_scroll', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feed_post_interaction',
                'indexes': [models.Index(fields=['user', '-created_at'], name='feed_post_i_user_id_ebc1a3_idx'), models.Index(fields=['post', '-created_at'], name='feed_post_i_post_id_25c874_idx'), models.Index(fields=['signal', '-created_at'], name='feed_post_i_signal_cfce67_idx'), models.Index(fields=['user', 'post', '-created_at'], name='feed_post_i_user_id_835866_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserGenreInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=20)),
                ('score', models.FloatField(default=0)),
                ('interactions_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feed_user_genre_interest',
                'indexes': [models.Index(fields=['user', '-score'], name='feed_user_g_user_id_0c2b70_idx'), models.Index(fields=['genre', '-score'], name='feed_user_g_genre_a6edd8_idx')],
                'unique_together': {('user', 'genre')},
            },
        ),
        migrations.CreateModel(
            name='UserTagInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('interactions_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interests', to='posts.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feed_user_tag_interest',
                'indexes': [models.Index(fields=['user', '-score'], name='feed_user_t_user_id_d1227a_idx'), models.Index(fields=['tag', '-score'], name='feed_user_t_tag_id_80b88c_idx')],
                'unique_together': {('user', 'tag')},
            },
        ),
    ]
