# Generated by Django 5.2.13 on 2026-05-08 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
        ('posts', '0004_tag_post_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostPoolRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_number', models.PositiveIntegerField()),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_recipients', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_pool_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feed_post_pool_recipient',
                'indexes': [models.Index(fields=['user', 'pool_number'], name='feed_post_p_user_id_36e42d_idx'), models.Index(fields=['post', 'pool_number'], name='feed_post_p_post_id_13949a_idx')],
                'unique_together': {('post', 'user', 'pool_number')},
            },
        ),
    ]
