# Generated by Django 5.2.13 on 2026-05-08 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_postpoolrecipient'),
        ('posts', '0004_tag_post_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterestprofile',
            name='last_session_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinterestprofile',
            name='time_decay_lambda',
            field=models.FloatField(default=0.08),
        ),
        migrations.CreateModel(
            name='FeedImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, default='', max_length=64)),
                ('bucket', models.CharField(default='targeted', max_length=30)),
                ('rank_position', models.PositiveIntegerField(default=0)),
                ('base_score', models.FloatField(default=0)),
                ('final_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_impressions', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_impressions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feed_impression',
                'indexes': [models.Index(fields=['user', '-created_at'], name='feed_impres_user_id_f6d1d3_idx'), models.Index(fields=['post', '-created_at'], name='feed_impres_post_id_a78c4a_idx'), models.Index(fields=['user', 'bucket', '-created_at'], name='feed_impres_user_id_880ba3_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserBanditArm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arm_type', models.CharField(choices=[('genre', 'Genre'), ('tag', 'Tag'), ('wildcard', 'Wildcard')], max_length=20)),
                ('arm_key', models.CharField(max_length=100)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('successes', models.PositiveIntegerField(default=0)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('total_reward', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bandit_arms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feed_user_bandit_arm',
                'indexes': [models.Index(fields=['user', 'arm_type'], name='feed_user_b_user_id_1b0b7e_idx'), models.Index(fields=['user', '-updated_at'], name='feed_user_b_user_id_2b70ac_idx')],
                'unique_together': {('user', 'arm_type', 'arm_key')},
            },
        ),
        migrations.CreateModel(
            name='ViralPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocity_score', models.FloatField(default=0)),
                ('engagement_growth', models.FloatField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('active_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='viral_state', to='posts.post')),
            ],
            options={
                'db_table': 'feed_viral_post',
                'indexes': [models.Index(fields=['active', '-velocity_score'], name='feed_viral__active_5a93f9_idx'), models.Index(fields=['-updated_at'], name='feed_viral__updated_e670d8_idx')],
            },
        ),
    ]
