# Generated by Django 5.2.13 on 2026-05-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_tag_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='background_color',
            field=models.CharField(default='#1A1A1A', max_length=7),
        ),
    ]
