# Generated by Django 5.2.13 on 2026-05-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audio_duration_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='posts/audio/'),
        ),
        migrations.AddField(
            model_name='post',
            name='audio_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
